import { ChangeEvent } from "react";

export interface ButtonInterface {
  children?: JSX.Element | JSX.Element[] | string,
  type?: string | Element,
  size?: string,
  icon?: string,
  flat?: string,
  iconColor?: string,
  className?: string,
  isLoading?: boolean,
  noPadding?: boolean,
  full?: boolean,
  textColor?: string,
  simple?: boolean,
  transparent?: boolean,
  noText?: boolean,
  shortcut?: boolean,
  quad?: boolean,
  disabled?: boolean,
  iconSize?: number,
  style?: any,
  iconOnly?: any,
  iconPosition?: any, 
  backgroundColor?: any,
  onClick?: (e: ChangeEvent<any>) => void,
}

export interface ButtonElementInterface {
  children?: JSX.Element | JSX.Element[] | string,
  size?: string,
  icon?: string,
  flat?: string,
  iconColor?: string,
  className?: string,
  isLoading?: boolean,
  full?: boolean,
  textColor?: string,
  simple?: boolean,
  transparent?: boolean,
  noText?: boolean,
  quad?: boolean,
  disabled?: boolean,
  iconSize?: number,
  style?: any,
  iconOnly?: any,  
  backgroundColor?: any,
  onClick?: (e: ChangeEvent<any>) => void,
}

export interface ButtonStyleInterface {
  flat?: string,
  type?: string | Element,
  simple?: boolean,
  textColor?: string,
  disabled?: boolean,
  transparent?: boolean,
  backgroundColor?: any,
}
